### ISSUE TITLE
Missing Data Directory

### ISSUE THREAD

**Issue by gowerc** [stefvanbuuren/fimdbook#1]
Hi @stefvanbuuren ,

I was trying to re-build your book  using `bookdown::render_book("index.Rmd", "bookdown::pdf_book")` in order to covert it into a pdf (personal preference as I find it easier to search through as well as  I like being able to add highlights and comments).  However when trying to re-build the book it appears to be looking for a data directory which is not included in the repository:

```
label: c85readdata1
Quitting from lines 11705-11705 (FIMD-bookdown.Rmd) 
Error in lookup.xport(file) : 
  unable to open file: 'No such file or directory'
```

Inspecting the code I can see:

```
## ----c85readdata1--------------------------------------------------------
library(foreign)
file.sas <- "data/c85/master85.xport"
original.sas <- read.xport(file.sas)
```

Would it be possible to either get the data directory added or if not would it be possible for you to upload a pdf version of the book?

Btw 

Thank you very much for publicly releasing such great content !

**Comment by stefvanbuuren** [comment]
The `master85.xport` data is not publicly available, so - as you found out - you will not be able to rebuild the entire book.

The repository is meant for study and documentation. Electronic versions of the book are available from the publisher at https://www.crcpress.com/Flexible-Imputation-of-Missing-Data-Second-Edition/Buuren/p/book/9781138588318.

Hope this helps. Stef.

**Comment by gowerc** [comment]
arr I see - thank you for explaining.
