### ISSUE TITLE
The Definition of Connectivity

### ISSUE THREAD

**Issue by drag05** [stefvanbuuren/fimdbook#3]
I find this book very interesting, as in my projects I have been having long conversations with my Clients regarding the treatment of missing data; I think that testing the ignorability of missing mechanisms should be the starting point of data imputation process. 

Nevertheless, the issue refers to the definition of *Connectivity* found on page 105 of [Flexible Imputation of Missing Data, 2nd Ed.](https://stefvanbuuren.name/fimd/) respectively, page 270 of [Handbook of Missing Data](https://www.taylorfrancis.com/books/handbook-missing-data-methodology-geert-molenberghs-garrett-fitzmaurice-michael-kenward-anastasios-tsiatis/10.1201/b17622) 

The Definition states (emphasis added): 

"*Connected and unconnected. A missing data pattern is said to be connected if **any observed data point** can be reached from **any other observed data point** through a sequence of horizontal or vertical moves (like the rook in chess)*" 

Looking at Figure 4.1 (reproduced from FIMD), the "File Matching" and "General" panels, I am unable to figure out how the last 3 observed values in the 3-rd column can be connected to any other observed values inside the data set unless the method:

- allowed passing through missing data records (in which case the above definition would be superfluous as any observed values in a data set become connectable) or,
- allowed column/row swapping (in which case the above definition seems incomplete by not including these allowances)
- uses the term "observed data point" as representing the entire column (vector) as a data point in the multi-dimensional cloud defined by the rows (in which case the above definition would not be needing the rook-like movement and, connectivity of two data points (vectors) defined this way would suffice if at least one component is connected)

Please advise, thank you!

![Figure 4.1](https://user-images.githubusercontent.com/39677929/106805704-051cb780-6635-11eb-9cbe-0c133468c1ec.png)

**Comment by stefvanbuuren** [comment]
All four patterns are connected. 

But imagine that we wouldn't have column 1 in the data. Then "File matching" and "General" become unconnected. Thus, we for these patterns we say that column 1 connects columns 2 and 3.

Unconnected pattern may occur in practice when we combine data. These lead to estimation problems, so preferably one should connect the observed data by fostering overlap in the observations.

**Comment by drag05** [comment]
@stefvanbuuren 

Thank you for your prompt answer!

To clarify, 

- the term "observed data point" found in the book refers to the entire column (my 3-rd bullet in the question above) and, 

- the term "connectivity" refers to row-wise overlapping of observed data between two columns located anywhere inside the dataset. 

If we join all 4 panels above and no rows/columns are removed in the process, a barrier formed by columns 2 and 3 in "File Matching" would not allow columns 3 in "Univariate" and column 3 in "General" to connect because no "rook-like" movement can cross that barrier (similar to column 2 in "Monotone" and column 1 in "General" etc.). 

A simple row-wise overlap however, will show these columns as connected.

Thank you!

**Comment by stefvanbuuren** [comment]
OK, thanks. Now closing.
